export const DEFAULT_CENTERS = [
  { l07: "BN0001.LTT", aeCode: "Ngo Si Lien", bus: "AHN", url: "" },
  { l07: "BN0002.TSN", aeCode: "Tu Son", bus: "AHN", url: "" },
  { l07: "HN0001.PHY", aeCode: "Pho Hue Junior", bus: "AHN", url: "" },
  { l07: "HN0002.THA", aeCode: "Thai Ha (center Láng Hạ)", bus: "AHN", url: "" },
  { l07: "HN0003.HQV", aeCode: "Hoang Quoc Viet", bus: "AHN", url: "" },
  { l07: "HN0004.LGI", aeCode: "Lieu Giai", bus: "AHN", url: "" },
  { l07: "HN0005.NVL", aeCode: "Nguyen Van Linh", bus: "AHN", url: "" },
  { l07: "HN0007.VQN", aeCode: "Van Quan", bus: "AHN", url: "" },
  { l07: "HN0010.MDH", aeCode: "My Dinh", bus: "AHN", url: "" },
  { l07: "HN0012.NHT", aeCode: "Hoang Mai", bus: "AHN", url: "" },
  { l07: "HN0014.TMI", aeCode: "Tan Mai", bus: "AHN", url: "" },
  { l07: "HN0015.VPU", aeCode: "Van Phu", bus: "AHN", url: "" },
  { l07: "HN0016.PDP", aeCode: "Phan Dinh Phung", bus: "AHN", url: "" },
  { l07: "HN0017.HNI", aeCode: "Ham Nghi", bus: "AHN", url: "" },
  { l07: "HN0018.VTP", aeCode: "Vu Tong Phan", bus: "AHN", url: "" },
  { l07: "HN0019.NTN", aeCode: "Nguyen Tuan", bus: "AHN", url: "" },
  { l07: "HN0021.NGD", aeCode: "Ngoai Giao Doan", bus: "AHN", url: "" },
  { l07: "HN0022.NVO", aeCode: "Nguyen Van Loc", bus: "AHN", url: "" },
  { l07: "HN0023.LDM", aeCode: "Linh Dam", bus: "AHN", url: "" },
  { l07: "HN0024.TCY", aeCode: "TIMES CITY", bus: "AHN", url: "" },
  { l07: "HN0025.LTT", aeCode: "Le Trong Tan", bus: "AHN", url: "" },
  { l07: "HN0026.VHG", aeCode: "Viet Hung", bus: "AHN", url: "" },
  { l07: "HN0027.OPK", aeCode: "Ocepark", bus: "AHN", url: "" },
  { l07: "HN0028.PVD", aeCode: "Pham Van Dong", bus: "AHN", url: "" },
  { l07: "HN0029.VPH", aeCode: "Vu Pham Ham", bus: "AHN", url: "" },
  { l07: "HN0030.AKH", aeCode: "An Khanh", bus: "AHN", url: "" },
  { l07: "HN0031.AHG", aeCode: "An Hung", bus: "AHN", url: "" },
  { l07: "HN0032.LLQ", aeCode: "Xuan Dieu (đổi thành Lạc Long Quân)", bus: "AHN", url: "" },
  { l07: "HN0033.DAH", aeCode: "HN33.DAH", bus: "AHN", url: "" },
  { l07: "HN0034.HTN", aeCode: "HN34.HTN", bus: "AHN", url: "" },
  { l07: "HY0001.ECP", aeCode: "Ecopark", bus: "AHN", url: "" },
  { l07: "HP0001.LHP", aeCode: "Hai Phong 1", bus: "AHN_HP", url: "" },
  { l07: "HP0002.HBT", aeCode: "Hai Phong 2", bus: "AHN_HP", url: "" },
  { l07: "HP0003.VIN", aeCode: "Hai Phong 3", bus: "AHN_HP", url: "" },
  { l07: "QN0001.HLG", aeCode: "Ha Long", bus: "AHN", url: "" },
  { l07: "VIN001.CTG", aeCode: "Vinh", bus: "AHN", url: "" },
  { l07: "VP0001.PCT", aeCode: "Vinh Phuc", bus: "AHN", url: "" },
  { l07: "TH0001.TPU", aeCode: "TH01.TPU", bus: "ATH", url: "" },
  { l07: "TN0001.LNQ", aeCode: "TN01.LNQ", bus: "ATN", url: "" },
  { l07: "PT0001.HVG", aeCode: "PT01.HVG", bus: "APT", url: "" },
  { l07: "AA", aeCode: "Apollo Advance -South", bus: "AHN", url: "" },
  { l07: "HN0200.ASP", aeCode: "ASP - HN", bus: "AHN", url: "" },
  { l07: "MKT LOCAL NORTH", aeCode: "MKT LOCAL NORTH", bus: "AHN", url: "" },
  { l07: "ZHN0000.GY", aeCode: "Cambridge", bus: "AHN", url: "" },
  { l07: "MKT HP", aeCode: "MKT HP", bus: "AHN_HP", url: "" },
  { l07: "TN0001.LNQ", aeCode: "MKT TN01.LNQ", bus: "ATN", url: "" },
  { l07: "PT0001.HVG", aeCode: "MKT PT01.HVG", bus: "APT", url: "" },
  { l07: "TH0001.TPU", aeCode: "MKT TH01.TPU", bus: "ATH", url: "" },
  { l07: "ZHN0000.GY", aeCode: "Contest", bus: "AHN", url: "" },
  { l07: "ZHN0000.GY", aeCode: "Contest", bus: "AHN_HP", url: "" }
];
